name: Test and deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{matrix.platform}}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        platform: [windows-latest]
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Test with tox
        run: poetry run tox


#  deploy:
#    name: Deploy Cloud Workflow
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Cloud SDK
#        uses: google-github-actions/auth@v0
#        with:
#          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          export_default_credentials: true
#      - name: Use gcloud CLI
#        run: |
#          gcloud workflows deploy myWorkflowFromGitHub \
#          --location europe-west3 \
#          --source app/test_workflow/get_wiki_article_workflow.yaml \
#          --project ${{ secrets.GCP_PROJECT_ID }} \
#          --labels "commit-sha=${{ github.sha }}" \
#          --service-account pramod-goyal@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
#
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: pramod-goyal@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cars-api
          gcloud config set run/region europe-west3

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy cars-api --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cars-api \
          --platform managed

      - uses: act10ns/slack@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          config: .github/config/slack.yml
          steps: ${{ toJson(steps) }}
          channel: '#test-alerts'
        if: always()